/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#2d1604",
        "inverse-surface": "#303030",
        "on-error": "#ffffff",
        "surface-bright": "#fcf9f8",
        outline: "#82746d",
        "secondary-fixed-dim": "#d8c3a7",
        "on-secondary-fixed-variant": "#53452f",
        secondary: "#6c5c44",
        "inverse-on-surface": "#f3f0f0",
        "surface-variant": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "secondary-fixed": "#f5dfc1",
        "on-primary": "#ffffff",
        "on-primary-container": "#eec1a4",
        "outline-variant": "#d4c3ba",
        "primary-fixed": "#ffdcc6",
        "on-surface-variant": "#50453e",
        "surface-container-high": "#eae7e7",
        "surface-container": "#f0eded",
        "on-tertiary-fixed": "#1c1c19",
        background: "#fcf9f8",
        "primary-container": "#6f4e37",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#565552",
        surface: "#fcf9f8",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474743",
        "on-secondary-fixed": "#251a07",
        "tertiary-fixed": "#e5e2dd",
        "on-background": "#1b1c1c",
        "inverse-primary": "#eabda0",
        tertiary: "#3e3e3b",
        "on-primary-fixed-variant": "#5f402a",
        "tertiary-fixed-dim": "#c8c6c2",
        "on-secondary-container": "#706048",
        "surface-container-low": "#f6f3f2",
        "error-container": "#ffdad6",
        "secondary-container": "#f2ddbf",
        primary: "#553722",
        "surface-tint": "#79573f",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e4e2e1",
        "surface-dim": "#dcd9d9",
        "on-tertiary-container": "#cccac5",
        "primary-fixed-dim": "#eabda0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "20px": "20px",
        full: "9999px",
        custom: "20px", // 👈 tambahkan untuk kelas rounded-custom
      },
      spacing: {
        "section-gap": "120px",
        "stack-sm": "16px",
        unit: "8px",
        "stack-md": "32px",
        "margin-mobile": "20px",
        gutter: "24px",
        "container-max": "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
      },
      boxShadow: {
        japandi: "0 10px 30px rgba(0, 0, 0, 0.08)", 
        premium: "0 10px 30px rgba(0,0,0,0.08)", // 👈 untuk shadow-japandi
      },
    },
  },
  plugins: [],
};